README: tun and mknod options and EULA reference
OpenVPN/as-docker pull request #16
Opened 2024-12-04 20:36 UTC by uddr

2024-12-05 11:52 UTC, flichtenheld requested changes

2024-12-05 11:52 UTC, flichtenheld commented on README.md
> +  --cap-add=CAP_MKNOD --cap-add=NET_ADMIN \
`--cap-add=MKNOD` See NET_ADMIN.

2024-12-09 21:13 UTC, uddr commented on README.md
> +  --cap-add=CAP_MKNOD --cap-add=NET_ADMIN \
actually both works
updated

2024-12-10 13:29 UTC, flichtenheld approved these changes

2024-12-10 13:51 UTC, merged